---
name: Run updatecli and open a PR with changes
author: PrefectHQ
description: This action will run updatecli and push the changes to git and will also open a PR
inputs:
  manifest-path:
    description: Path to the updatecli manifest file
    default: ".github/updatecli/manifest-minor.yaml"
    required: true
  run-helm-docs:
    description: Run helm-docs
    default: "false"
    required: true
  run-type:
    description: The type of updatecli run to perform (major or minor)
    default: "minor"
    required: true
runs:
  using: composite
  steps:
    - name: Configure git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
      shell: bash

    - name: Get current date
      run: |
        echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      shell: bash

    - name: Determine branch name
      run: |
        echo "BRANCH_NAME=dependency-version-${{ inputs.run-type }}-$DATE" >> $GITHUB_ENV
      shell: bash

    - name: Create branch for dependency version updates
      run: |
        git checkout -b $BRANCH_NAME
      shell: bash

    - name: Install updatecli in the runner
      uses: updatecli/updatecli-action@v2

    - name: Run updatecli in apply mode
      run: |
        updatecli apply --config ${{ inputs.manifest-path }} --experimental
        if [[ $(git diff --name-only | wc -l) -eq 0 ]]; then
          echo "No changes detected, exiting"
          echo "CHANGES=false" >> $GITHUB_ENV
          exit 0
        else
          echo "CHANGES=true" >> $GITHUB_ENV
        fi
        git add .
        git commit -m $BRANCH_NAME
        git push --set-upstream origin $BRANCH_NAME
      env:
        GITHUB_TOKEN: ${{ github.token }}
      shell: bash

    - name: Create PR
      if: env.CHANGES == 'true'
      run: |
        git checkout $BRANCH_NAME
        gh pr create --base main --title $BRANCH_NAME -f --label soc2
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash
